on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"deps","section":"Dependencies","hidden":false},{"type":"style","section":"style","hidden":false},{"type":"refactor","section":"Refactor","hidden":false},{"type":"perf","section":"Performance","hidden":false},{"type":"test","section":"Test","hidden":false},{"type":"ci","section":"Continuous Integration","hidden":false},{"type":"build","section":"Build","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          
          
          
          